# Generated by Django 4.2.4 on 2023-12-15 11:04

from django.db import migrations, models
import django.db.models.deletion
import apps.institutions.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='institution_types',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'instituition_types',
            },
        ),
        migrations.CreateModel(
            name='institutions',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('leader_name', models.CharField(max_length=255, null=True)),
                ('address', models.TextField()),
                ('email', models.CharField(db_index=True, max_length=100, null=True, unique=True)),
                ('phone_number', models.CharField(max_length=15, unique=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to=apps.institutions.models.upload)),
                ('status', models.CharField(choices=[('1', 'active'), ('2', 'suspended'), ('3', 'inactive')], default='1', max_length=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('institution_type_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='institutions.institution_types')),
            ],
            options={
                'db_table': 'institutions',
            },
        ),
        migrations.CreateModel(
            name='villages',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'villages',
            },
        ),
        migrations.CreateModel(
            name='pic_institutions',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nik', models.CharField(db_index=True, max_length=16, null=True, unique=True)),
                ('name', models.CharField(max_length=255, null=True)),
                ('gender', models.CharField(choices=[('1', 'male'), ('2', 'female')], db_index=True, default='1', max_length=1, null=True)),
                ('date_of_birth', models.DateField(db_index=True, null=True)),
                ('address', models.TextField(null=True)),
                ('phone_number', models.CharField(max_length=15, null=True, unique=True)),
                ('display_photo', models.ImageField(blank=True, null=True, upload_to=apps.institutions.models.upload)),
                ('photo_identity_number', models.ImageField(blank=True, null=True, upload_to='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('institution_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='institutions.institutions')),
                ('village_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='institutions.villages')),
            ],
            options={
                'db_table': 'pic_institutions',
            },
        ),
        migrations.CreateModel(
            name='pic_institution_data_changes',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('institution_id', models.BigIntegerField(max_length=20, null=True)),
                ('nik', models.CharField(max_length=16, null=True)),
                ('name', models.CharField(max_length=255, null=True)),
                ('gender', models.CharField(choices=[('1', 'male'), ('2', 'female')], db_index=True, default='1', max_length=1, null=True)),
                ('date_of_birth', models.DateField(db_index=True, null=True)),
                ('address', models.TextField(null=True)),
                ('phone_number', models.CharField(max_length=15, null=True, unique=True)),
                ('display_photo', models.ImageField(default=None, null=True, upload_to='')),
                ('photo_identity_number', models.ImageField(default=None, null=True, upload_to=apps.institutions.models.upload)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('pic_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='institutions.pic_institutions')),
                ('village_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='institutions.villages')),
            ],
            options={
                'db_table': 'pic_institution_data_changes',
            },
        ),
        migrations.CreateModel(
            name='institution_verifications',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('1', 'pending'), ('2', 'accepted'), ('3', 'rejected')], db_index=True, default='1', max_length=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('institution_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='institutions.institutions')),
                ('verified_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employees.employees')),
            ],
            options={
                'db_table': 'institution_verification',
            },
        ),
        migrations.CreateModel(
            name='institution_data_changes',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('institution_type_id', models.BigIntegerField(max_length=20)),
                ('leader_name', models.CharField(max_length=255, null=True)),
                ('name', models.CharField(max_length=255)),
                ('address', models.TextField()),
                ('phone_number', models.CharField(max_length=15, unique=True)),
                ('logo', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('1', 'active'), ('2', 'suspended'), ('3', 'inactive')], default='1', max_length=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('institution_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='institutions.institutions')),
            ],
            options={
                'db_table': 'institution_data_changes',
            },
        ),
    ]
