# Generated by Django 4.2.4 on 2023-12-15 11:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('institutions', '0001_initial'),
        ('schools', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='integrations',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('1', 'pending'), ('2', 'accepted'), ('3', 'rejected')], db_index=True, default='1', max_length=1)),
                ('status_read', models.CharField(choices=[('0', 'not read yet'), ('1', 'has been read')], db_index=True, default='0', max_length=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('pic_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='institutions.pic_institutions')),
                ('school_id', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='schools.schools')),
            ],
            options={
                'db_table': 'integrations',
            },
        ),
        migrations.CreateModel(
            name='institution_schools',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('deleted_at', models.DateTimeField(default=None, null=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='institutions.pic_institutions')),
                ('institution_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='institutions.institutions')),
                ('school_id', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='schools.schools')),
            ],
            options={
                'db_table': 'institution_schools',
            },
        ),
        migrations.CreateModel(
            name='institution_school_verifications',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('1', 'pending'), ('2', 'accepted'), ('3', 'rejected')], db_index=True, default='1', max_length=1)),
                ('verified_by', models.BigIntegerField(default=None, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('institution_school_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='integrations.institution_schools')),
            ],
            options={
                'db_table': 'institution_school_verification',
            },
        ),
    ]
