# Generated by Django 4.2.4 on 2023-12-16 09:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('institutions', '0001_initial'),
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CostumUser',
            fields=[
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=255)),
                ('email', models.CharField(db_index=True, max_length=100, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('is_yayasan', models.BooleanField(default=False)),
                ('is_staff', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='pic_user_data_changes',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('pic_id', models.BigIntegerField(max_length=20)),
                ('password', models.CharField(max_length=255)),
                ('email', models.CharField(db_index=True, max_length=100, unique=True)),
                ('email_verified_at', models.DateTimeField(default=None, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('pic_user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'pic_user_data_changes',
            },
        ),
        migrations.CreateModel(
            name='log_pic_users',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('action', models.CharField(choices=[('1', 'Login'), ('2', 'Logout')], max_length=1)),
                ('last_ip_address', models.CharField(blank=True, max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('pic_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'log_pic_users',
            },
        ),
        migrations.CreateModel(
            name='log_employee_users',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('action', models.CharField(choices=[('1', 'Login'), ('2', 'Logout')], max_length=1)),
                ('last_ip_address', models.CharField(max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('employee_user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'log_employee_users',
            },
        ),
        migrations.CreateModel(
            name='employee_user_data_changes',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('employee_id', models.BigIntegerField(db_index=True, max_length=20)),
                ('email', models.CharField(db_index=True, max_length=100, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('email_verified_at', models.DateTimeField(default=None, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'employee_user_data_changes',
            },
        ),
        migrations.CreateModel(
            name='pic_users',
            fields=[
                ('costumuser_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('email_verified_at', models.DateTimeField(default=None, null=True)),
                ('pic_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='institutions.pic_institutions')),
            ],
            options={
                'db_table': 'pic_users',
            },
            bases=('Account.costumuser',),
        ),
        migrations.CreateModel(
            name='employee_users',
            fields=[
                ('costumuser_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('email_verified_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('employee_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='employees.employees')),
            ],
            options={
                'db_table': 'employee_users',
            },
            bases=('Account.costumuser',),
        ),
    ]
