# Generated by Django 4.2.4 on 2023-12-15 11:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='education_levels',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('deleted_at', models.DateTimeField(default=None, null=True)),
            ],
            options={
                'db_table': 'education_levels',
            },
        ),
        migrations.CreateModel(
            name='schools',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('npsn', models.CharField(db_index=True, max_length=50, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('dns', models.CharField(db_index=True, max_length=255, unique=True)),
                ('link_maps', models.CharField(default=None, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('deleted_at', models.DateTimeField(default=None, null=True)),
                ('education_level_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schools.education_levels')),
            ],
            options={
                'db_table': 'schools',
            },
        ),
    ]
