# Generated by Django 4.2.4 on 2023-12-15 11:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='employees',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nik', models.CharField(db_index=True, max_length=16)),
                ('name', models.CharField(max_length=255)),
                ('display_photo', models.ImageField(blank=True, null=True, upload_to='asset/employees/')),
                ('status', models.CharField(choices=[('1', 'active'), ('2', 'suspended'), ('3', 'inactive')], db_index=True, default='1', max_length=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'employees',
            },
        ),
        migrations.CreateModel(
            name='employee_data_changes',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nik', models.CharField(db_index=True, max_length=16)),
                ('name', models.CharField(max_length=255)),
                ('display_photo', models.TextField(default=None, null=True)),
                ('status', models.CharField(choices=[('1', 'active'), ('2', 'suspended'), ('3', 'inactive')], db_index=True, default='1', max_length=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employees.employees')),
            ],
            options={
                'db_table': 'employee_data_changes',
            },
        ),
    ]
